#!/usr/bin/env python3

import skilstak.colors as c

"""Not yo Grandma's Hello World"""

def print_plain(message="hello world"):
    """prints messgae plainish"""
    print message

if __name__ == "__main__":
    print_plain()
