#!/usr/bin/env python3

import skilstak.colors as c
import time

def print_plain(message):
    print(c.clear + c.rc() + message + c.reset)

def print_multi(message):
    while True:
        print(c.clear + c.multi(message))
        time.sleep(0.5)

def print_color(message):
    print(c.clear)
    while True:
        print(c.rc() + message + c.reset, end=" ")

def print_turtle(message):
    print(c.clear)
    #prints 'turtle' forever
    while True:
        print(c.rc() + message + c.reset, end=" ")
    time.sleep(0.49999)

if __name__ == '__main__':
    import sys

    who = "world"
    option = ""
    message = ""

    if len(sys.argv) > 2:
        option = sys.argv[1]
        who = sys.argv[2]
    elif len(sys.argv) == 2:
        if sys.argv[1].startswith("-"):
            option = sys.argv[1]
        else:
            who = sys.argv[1];

    message = "Hello " + who + "!";

    try:
        if option == "-m":
            print_multi(message)
        elif option == "-c":
            print_color(message)
        elif option == "-t":
            print_turtle(message)
        else: 
            print_plain(message)
    except KeyboardInterrupt:
        exit()
