#!/usr/bin/env python3

import skilstak.colors as c

def color():
    print(c.clear)
    while True:
        print(c.rc() + "Hello World" + c.reset, end=" ")

def hello(kind='plain'):
    try:
        pass
    except KeyboardInterrupt:
        return

if __name__ == '__main__':
    import sys
    if len(sys.argv) == 1:
        hello()
    else:
        hello(sys.argv[1])
